steps:

  - id: 'Rodando docker-compose'
    name: 'gcr.io/$PROJECT_ID/docker-compose:1.24.0'
    args: ['-f', 'docker-compose.cbuild.yaml', 'up', '-d']

  - id: 'Rodando o composer'
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'micro-videos-app', 'composer', 'install']

  - id: 'Copiando o .env'
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'micro-videos-app', 'cp', '.env.example', '.env']

  - id: 'Copiando o .env.testing'
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'micro-videos-app', 'cp', '/var/www/.docker/app/.env.testing', '.env.testing']

  - id: 'Gerando o key do laravel'
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'micro-videos-app', 'php', '/var/www/artisan', 'key:generate']

  - id: 'Rodando migrations'
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'micro-videos-app', 'php', '/var/www/artisan', 'migrate']

  - id: 'Rodando phpunit'
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'micro-videos-app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml']
